/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _AIRPORTS_H_RPCGEN
#define _AIRPORTS_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXWORDLEN 255
#define MAXCODLEN 3

typedef char *word;

typedef char *cod;

typedef struct airportstruct *airportlist;

struct airportstruct {
	word name;
	cod code;
	double distance;
	airportlist next;
};
typedef struct airportstruct airportstruct;

struct position {
	double latitude;
	double longitude;
};
typedef struct position position;

struct airport_list {
	int errno;
	union {
		airportlist list;
	} airport_list_u;
};
typedef struct airport_list airport_list;

#define AIRPORTPROG 0x20000123
#define AIRPORTVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define AIRPORTS 1
extern  airport_list * airports_1(struct position *, CLIENT *);
extern  airport_list * airports_1_svc(struct position *, struct svc_req *);
extern int airportprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define AIRPORTS 1
extern  airport_list * airports_1();
extern  airport_list * airports_1_svc();
extern int airportprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_word (XDR *, word*);
extern  bool_t xdr_cod (XDR *, cod*);
extern  bool_t xdr_airportlist (XDR *, airportlist*);
extern  bool_t xdr_airportstruct (XDR *, airportstruct*);
extern  bool_t xdr_position (XDR *, position*);
extern  bool_t xdr_airport_list (XDR *, airport_list*);

#else /* K&R C */
extern bool_t xdr_word ();
extern bool_t xdr_cod ();
extern bool_t xdr_airportlist ();
extern bool_t xdr_airportstruct ();
extern bool_t xdr_position ();
extern bool_t xdr_airport_list ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_AIRPORTS_H_RPCGEN */
