/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "airports.h"


void
airportprog_1(char *host)
{
  CLIENT *clnt;
  airport_list  *result_1;
  struct position  airports_1_arg;

#ifndef DEBUG
  clnt = clnt_create (host, AIRPORTPROG, AIRPORTVERS, "udp");
  if (clnt == NULL) {
	clnt_pcreateerror (host);
	exit (1);
  }
#endif  /* DEBUG */

  airports_1_arg.latitude=40.352206;
  airports_1_arg.longitude =-74.657071;
  printf("past\n");
  result_1 = airports_1(&airports_1_arg, clnt);
  if (result_1 == (airport_list *) NULL) {
	clnt_perror (clnt, "call failed");
	exit(1);
  }
  if(result_1->errno>0){
	clnt_freeres(clnt, (xdrproc_t)xdr_airport_list, (char *)result_1);
	exit(1);
  }
  airportlist l=result_1->airport_list_u.list;
  while(l){
	printf("%s ", l->name);
	printf("%s ", l->code);
	printf("%.0f\n", l->distance);
	l=l->next;
  }
  printf("way past\n");
  xdr_free((xdrproc_t)xdr_airport_list, (char *)result_1);
#ifndef DEBUG
  clnt_destroy (clnt);
#endif   /* DEBUG */
}


int
main (int argc, char *argv[])
{
  char *host;

  if (argc < 2) {
	printf ("usage: %s server_host\n", argv[0]);
	exit (1);
  }
  host = argv[1];
  airportprog_1 (host);
  exit (0);
}
