/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _PLACES_H_RPCGEN
#define _PLACES_H_RPCGEN

#include <rpc/rpc.h>


#ifdef __cplusplus
extern "C" {
#endif

#define MAXNAMELEN 255
#define MAXSTATELEN 2
#define MAXCODELEN 3

typedef char *placename;

typedef char *statename;

typedef char *codename;

typedef struct placestruct *placeslist;

struct placestruct {
	codename code;
	placename place;
	statename state;
	double longitude;
	double latitude;
	double distance;
	placeslist next;
};
typedef struct placestruct placestruct;

struct location {
	placename city;
	statename state;
	placename host;
};
typedef struct location location;

struct places_list {
	int errno;
	union {
		placeslist list;
	} places_list_u;
};
typedef struct places_list places_list;

#define PLACEPROG 0x2000001D
#define PLACEVERS 1

#if defined(__STDC__) || defined(__cplusplus)
#define PLACES 1
extern  places_list * places_1(struct location *, CLIENT *);
extern  places_list * places_1_svc(struct location *, struct svc_req *);
extern int placeprog_1_freeresult (SVCXPRT *, xdrproc_t, caddr_t);

#else /* K&R C */
#define PLACES 1
extern  places_list * places_1();
extern  places_list * places_1_svc();
extern int placeprog_1_freeresult ();
#endif /* K&R C */

/* the xdr functions */

#if defined(__STDC__) || defined(__cplusplus)
extern  bool_t xdr_placename (XDR *, placename*);
extern  bool_t xdr_statename (XDR *, statename*);
extern  bool_t xdr_codename (XDR *, codename*);
extern  bool_t xdr_placeslist (XDR *, placeslist*);
extern  bool_t xdr_placestruct (XDR *, placestruct*);
extern  bool_t xdr_location (XDR *, location*);
extern  bool_t xdr_places_list (XDR *, places_list*);

#else /* K&R C */
extern bool_t xdr_placename ();
extern bool_t xdr_statename ();
extern bool_t xdr_codename ();
extern bool_t xdr_placeslist ();
extern bool_t xdr_placestruct ();
extern bool_t xdr_location ();
extern bool_t xdr_places_list ();

#endif /* K&R C */

#ifdef __cplusplus
}
#endif

#endif /* !_PLACES_H_RPCGEN */
