/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "places.h"

bool_t
xdr_placename (XDR *xdrs, placename *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXNAMELEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_statename (XDR *xdrs, statename *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXSTATELEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_codename (XDR *xdrs, codename *objp)
{
	register int32_t *buf;

	 if (!xdr_string (xdrs, objp, MAXCODELEN))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_placeslist (XDR *xdrs, placeslist *objp)
{
	register int32_t *buf;

	 if (!xdr_pointer (xdrs, (char **)objp, sizeof (struct placestruct), (xdrproc_t) xdr_placestruct))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_placestruct (XDR *xdrs, placestruct *objp)
{
	register int32_t *buf;

	 if (!xdr_codename (xdrs, &objp->code))
		 return FALSE;
	 if (!xdr_placename (xdrs, &objp->place))
		 return FALSE;
	 if (!xdr_statename (xdrs, &objp->state))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->longitude))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->latitude))
		 return FALSE;
	 if (!xdr_double (xdrs, &objp->distance))
		 return FALSE;
	 if (!xdr_placeslist (xdrs, &objp->next))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_location (XDR *xdrs, location *objp)
{
	register int32_t *buf;

	 if (!xdr_placename (xdrs, &objp->city))
		 return FALSE;
	 if (!xdr_statename (xdrs, &objp->state))
		 return FALSE;
	 if (!xdr_placename (xdrs, &objp->host))
		 return FALSE;
	return TRUE;
}

bool_t
xdr_places_list (XDR *xdrs, places_list *objp)
{
	register int32_t *buf;

	 if (!xdr_int (xdrs, &objp->errno))
		 return FALSE;
	switch (objp->errno) {
	case 0:
		 if (!xdr_placeslist (xdrs, &objp->places_list_u.list))
			 return FALSE;
		break;
	default:
		break;
	}
	return TRUE;
}
