/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "places.h"


void
placeprog_1(char *host, struct location place)
{
	CLIENT *clnt;
	places_list  *result_1;
	struct location  places_1_arg;
	places_1_arg=place;
	
	clnt = clnt_create (host, PLACEPROG, PLACEVERS, "udp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}

	
	
	result_1 = places_1(&places_1_arg, clnt);
	if (result_1 == (places_list *) NULL) {
		clnt_perror (clnt, "call failed");
	}
	
	placeslist p = result_1->places_list_u.list;
	if(result_1->errno>0){
	  printf("Did not find matching city.\n", result_1->errno);
	  clnt_freeres (clnt,(xdrproc_t) xdr_places_list, (char *)result_1);
	  exit(1);
	}

	/*
		printf("City:%s\t",p->place);
	printf("State:%s\t",p->state);
	printf("Longitude:%.2f\t",p->longitude);
	printf("Latitude:%.2f\t",p->latitude);
	printf("Distance:%.0fmiles\n",p->distance);
	printf("Location found! Nearest airports:\n");
	p=p->next;
	*/
	while(p){
	  printf("Code:%s\t",p->code);
	  printf("City:%s\t",p->place);
	  printf("State:%s\t",p->state);
	  //printf("%f ",p->longitude);
	  //printf("%f ",p->latitude);
	  printf("%.0fmiles\n",p->distance);	  
	  p=p->next;
	}

	clnt_freeres (clnt,(xdrproc_t) xdr_places_list, (char *)result_1);
	clnt_destroy (clnt);

}


int
main (int argc, char *argv[])
{
  char *host;
  char *place;
  char *state;
  
  if (argc < 4) {
	printf ("usage: %s server_host city state\n", argv[0]);
	exit (1);
  }
  host = argv[1];
  place = argv[2];
  state = argv[3];
  struct location loc;
  loc.city=place;
  loc.state=state;
  loc.host=host;
  placeprog_1 (host, loc);
  exit (0);
}
